# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Task_UI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'WillBottomSheet'
  # Pods for Task_UI

end
